### PR TITLE
Create build.py

### PR DESCRIPTION
**Pull request by Auxilus**
It automatically installs the package 
`Apt install ./NAME ` no longer needed...
Maybe run build.py through build.sh
Or directly as ./build.py

### CODE REVIEW

**Comment by cocodevienne** [comment]
Direct execution of build.py is simpler I think!:) Thanks for the patch!🙏@Auxilus

**Comment by Auxilus** [comment]
No probs...✌

**Comment by Auxilus** [comment]
@cocodevienne How do I add your repo  to termux?
Can you please elaborate??
Thanks...

**Comment by cocodevienne** [comment]
You don't. Follow the command in the README.rst. I'm slowly getting behind the secret of making my own repo. I would have to format mine to be in a format that `APT` understands and then edit `sources.list` located in `/data/data/com.termux/files/usr/etc/apt`. For now use `wget [URL]`. @Auxilus

**Comment by cocodevienne** [comment]
What in the world is that?@Auxilus

**Comment by cocodevienne** [comment]
Link to source?@Auxilus

**Comment by Auxilus** [comment]
It's a pentesting tool used for flood attacks 
https://github.com/antirez/hping

**Comment by cocodevienne** [comment]
You could compile it yourself in the "termux way" outlined in the README of the main app repo and package repo. Why don't you join the Gitter channel and ask them there. I really only do Python and only do C for cross-compilation like cython etc. If I can help in any other way, just tell me!:)@Auxilus I'm also on Gitter btw.

**Comment by Auxilus** [comment]
Yeah I am on gitter....And I asked that question there...Thanks for help

**Comment by cocodevienne** [comment]
You might want to look at this: http://github.com/cocodevienne/rshell-termux
@Auxilus It might help you figure out how to compile packages with C source.

**Comment by Auxilus** [comment]
Sure thanks

**Comment by cocodevienne** [comment]
No probs dude!👌@auxilus

**Pull request merged**
